language: go

go: 1.4.2

install:
    - go get github.com/gorilla/mux
    - go get github.com/mattn/goveralls
    - go get golang.org/x/net/websocket
    - go get golang.org/x/tools/cmd/cover

    - export GOPATH=${TRAVIS_BUILD_DIR}:$GOPATH

script:
    - PATH="$HOME/gopath/bin:$PATH"
    - scripts/coverage --coveralls
